baseETCD: &baseETCD
  root: GOGS # etcd key前缀
  user: "" # etcd用户
  password: "" # etcd密码
  addr: ["127.0.0.1:2379"] # etcd服务器地址
  ttl: 5 # etcd超时时间秒

rpc:
  timeout: 5 # rpc超时时间秒
  listenRetryInterval: 5 # rpc监听重试时间秒
  gateSessionCache: 4096 # 网关session发送缓存大小
  clusterSessionCache: 4096 # 集群session发送缓存大小
  clusterSessionHeartbeat: 30 # 集群session检查心跳间隔秒
  clientSessionCache: 64 # 客户端session发送缓存大小
  clusterCerInterval: 2 # 集群证书更新间隔秒
  actorGroups: 128 # actor分组数量
